import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { Country, Covid19ApiResponse } from '../types'
import CountryCard from '../components/CountryCard'

type Props = {
  data: any
  countries: Array<Country>
}

const Home: NextPage<Props> = ({ data, countries }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lowest Covid Countries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.headersInfo}>
          <p>最終更新日: {data.Date.split('T')[0]}</p>
          <p>5000人以下の国: {countries.length}</p>
        </div>
        <p className={styles.headersTitle}>感染者が少ない国</p>
        <div className={styles.countriesWrapper}>
          {countries.map((country) => {
            return (
              <Link key={country.ID} href={`/${country.Slug}`}>
                <a>
                 <CountryCard country={country}/>
                </a>
              </Link>
            )
          })}
        </div>
      </main>
      <footer></footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch('https://api.covid19api.com/summary')
  const data: Covid19ApiResponse = await res.json()
  const countries = data.Countries.filter((country) => country.TotalConfirmed < 20000)
  countries.sort((a, b) => (a.TotalConfirmed > b.TotalConfirmed ? 1 : -1))
  return {
    props: { data, countries }
  }
}

export default Home
